### ISSUE TITLE
Exibição do campo sala para empresas com mais de 1 sala cadastrada

### ISSUE THREAD

**Issue by betoscofield** [eucelso/condominiums-be#10]
[por favor não excluir issue sem concluirmos o assunto]

Variantes:
- Condômino com 2 salas ou mais no mesmo andar e mesma torre
- Condômino com 2 salas ou mais em andares diferentes na mesma torre
- Condômino com 2 salas ou mais no mesmo andar em ambas as torres
- Condômino com 2 salas ou mais em andares diferentes em ambas as torres

Abrir o campo para digitação sem perder a base já cadastrada ou exibir o que o usuário cadastrou no admin utilizando como exemplo mencionado pelo gestor:
Condomino 1:
Torre 1 e 2
Andar 1 - Sala 101
Andar 2 - Sala 201

Torre 1
Andar 3 - Salas 301, 302 e 303

**Comment by eucelso** [comment]
Fechando pois temos o mesmo aberto no outro repo e ja vamos atuar lá
