### ISSUE TITLE
Aumentar tamanho do logo da empresa

### ISSUE THREAD

**Issue by betoscofield** [eucelso/condominiums-be#2]
Aumentar proporcionamente tamanho do logo da empresa
![Captura de Tela 2024-10-21 às 19 51 08](https://github.com/user-attachments/assets/0dc43b99-41f0-41a5-843e-cc6a80efff4e)

**Comment by eucelso** [comment]
Aumentado o tamanho do logo 

<img width="1715" alt="image" src="https://github.com/user-attachments/assets/7c4bd6ec-e4fd-431a-a228-f9aa9593fd93">
