### ISSUE TITLE
Inserir icone botão home para a home do site 

### ISSUE THREAD

**Issue by betoscofield** [eucelso/condominiums-be#3]
inserir botão formato icone (casa) de acordo com cada endereço de localização de totem

**Comment by betoscofield** [comment]
botão deverá ficar do lado esquerdo no lugar do botao voltar

**Comment by eucelso** [comment]
<img width="1146" alt="image" src="https://github.com/user-attachments/assets/25d02d2e-28ea-446c-acd1-1dada2312a91">

<img width="1066" alt="image" src="https://github.com/user-attachments/assets/9a7e30a9-b6c1-4138-9e20-56e7b5d38ab0">


Adicionado botao home em cima e em baixo assim como o voltar
