### ISSUE TITLE
Verificar a possibilidade de inclusão de icone Whatsapp

### ISSUE THREAD

**Issue by betoscofield** [eucelso/condominiums-be#6]
Verificar a possibilidade de inclusão de icone Whatsapp pequeno na frente do numero para dar entender que é um link na versão mobile

**Comment by eucelso** [comment]
<img width="929" alt="image" src="https://github.com/user-attachments/assets/9720bb62-c29f-43c7-8348-9b557fd6821a">

Adicionado
