### ISSUE TITLE
Não exibir todas as categorias em Öutros"

### ISSUE THREAD

**Issue by betoscofield** [eucelso/condominiums-be#8]
Atualmente a o botão outros esta exibindo todas as categorias e deve exibir somente as categorias Outros.

**Comment by betoscofield** [comment]
![Uploading Captura de Tela 2024-10-22 às 09.24.35.png…]()

**Comment by betoscofield** [comment]
![Captura de Tela 2024-10-22 às 09 24 35](https://github.com/user-attachments/assets/12902284-52f3-4b2d-b7e2-041d0b057f11)

**Comment by eucelso** [comment]
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/2174ac02-4d63-46b5-8eeb-92f4b2699fbc">


Finalizado
